#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <time.h>
#include <string.h>
#include <unistd.h>

#include "placentastdlib.h"

// an "open circuit" flow model of the placenta. We put in a given flow and hold the outlet compartment at fixed volume.
// mostly was done for testing and timing purposes


int run(void)
{
    // these three numbers come out of the 'placenta.m' code in Matlab, and are saved in 'placenta.mat' (Matlab folder), but it's easier to enter them by hand than bother loading them in.

    // number of *arterial* nodes
    int num_Anodes = 63608;
    // number of *arterial* elements
    int num_Aelts = 63607;
    // number of terminal nodes and elements
    int num_term = 31803;

    // compliance and volume vectors for entire network (arterial and venous)
    float C[2*num_Anodes];
    float V[2*num_Anodes];

    // the following are generated by "placenta.m" in Matlab folder, and are read in here. see that code to understand what they are.
    // vector of resistances (first arterial, then venous, then terminal elements)
    float Rvec[2*num_Aelts + num_term];
    // links and "node elements" (node_elts), flattened from their Matlab matrix form into vectors (stacked column wise)
    int templinks[2*(2*num_Aelts + num_term)]; // the nodes attached to each element in the joint network
    int tempnode_elts[3*(2*num_Anodes)]; // the elements attached to each node in the joint network. Can have at most three per node. when it's less than 3, the others are zero.
    int i = 0;

    // flow vector (same order as Rvec)
    float Qvec[2*num_Aelts + num_term];
    // pressure
    float P[2*num_Anodes];
    float V_new[2*num_Anodes];
    float time_spent=0.0;

    float dt;
    int ind;
    int jones;
    int k;
    float Q_bc;
    float ampl;

    float Q_bct;
    float flow;
    char filename[100];
    char ending[] = ".txt";


    // read in vectors generated by placenta.m (then saved as txt files, of course)
    FILE *file;

    file = fopen("C.txt", "r");

    for (i=0; i<2*num_Anodes; i++)
    {
        fscanf(file, "%e", &C[i]);
    }
    
    fclose(file);


    file = fopen("V.txt", "r");

    for (i=0; i<2*num_Anodes; i++)
    {
        fscanf(file, "%e", &V[i]);
    }
    
    fclose(file);


    file = fopen("Rvec.txt", "r");

    for (i=0; i<2*num_Aelts + num_term; i++)
    {
        fscanf(file, "%e", &Rvec[i]);
    }
    
    fclose(file);


    file = fopen("templinks.txt", "r");

    for (i=0; i<2*(2*num_Aelts + num_term); i++)
    {
        fscanf(file, "%d", &templinks[i]);
    }
    
    fclose(file);


    file = fopen("tempnode_elts.txt", "r");

    for (i=0; i<3*(2*num_Anodes); i++)
    {
        fscanf(file, "%d", &tempnode_elts[i]);
    }
    
    fclose(file);


    dt = 1E-7; // need a time step THIS small to work well!
    Q_bc = 0.201*24.2; // input flow
    ampl = 1; // we drive it with a sine wave, and this is it's amplitude (the drive flow sine function)

    // initiate pressure
    for (i = 0; i<(2*num_Anodes); i++)
    {
        P[i] = V[i]/C[i];
    }

    // initiate flow
    for (i = 0; i<(2*num_Aelts+num_term); i++)
    {
        Qvec[i] = (P[templinks[i]-1] - P[templinks[2*num_Aelts + num_term+i]-1])/Rvec[i];
    }

    clock_t begin = clock();

    // loop over time
    for (ind = 0; ind<1001; ind++)
    {
        Q_bct = Q_bc + ampl*sin(2*pi/0.5*ind*dt); // evaluate t-dep flow

        // evolve the volumes
        for (jones = 0; jones<2*num_Anodes; jones++)
        {
            flow = 0;

            for (k = 0; k<3; k++)
            {
                if ((templinks[tempnode_elts[jones+k*2*num_Anodes]-1]==jones+1) && (tempnode_elts[jones+k*2*num_Anodes]!=0)) {
                    flow = flow - Qvec[tempnode_elts[jones+k*2*num_Anodes]-1];
                } else if ((templinks[tempnode_elts[jones+k*2*num_Anodes]-1+2*num_Aelts + num_term]==jones+1) && (tempnode_elts[jones+k*2*num_Anodes]!=0)) {
                    flow = flow + Qvec[tempnode_elts[jones+k*2*num_Anodes]-1];
                }
            }

            if (jones==0) {
                flow = flow + Q_bct; // inlet
            } else if (jones==num_Anodes) {
                flow = 0; // outlet
            }
            if (fabsf(flow)<=1E-10) {
                flow = 0; // noise filter
            }

            V_new[jones] = V[jones] + dt*flow;
        }

        for (i = 0; i<(2*num_Anodes); i++)
            P[i] = V_new[i]/C[i]; // get the pressures

        for (i = 0; i<(2*num_Aelts+num_term); i++) // the flows
            Qvec[i] = (P[templinks[i]-1] - P[templinks[i+2*num_Aelts + num_term]-1])/Rvec[i];

        for (i=0; i<2*num_Anodes; i++)
            V[i] = V_new[i]; // and recycle volume


        // write data
        if (ind % 1000 == 0){
            chdir("data");
            itoa(ind,filename,10);
            strcat(filename,ending);

            file=fopen(filename,"w");
            for(i=0;i<2*num_Anodes;i++) {
                fprintf(file,"%e\n",V[i]); // only record volume, from which you can get everything else
            }
            fclose(file);
            chdir("..");
        }



    }


    clock_t end = clock();

    time_spent += (float)(end - begin) / CLOCKS_PER_SEC;

    printf("The elapsed time is %f seconds", time_spent);




    return 0;
}

int main(void)
{
    return run();
}
